export const headers = [
  { label: 'Date', key: 'txnDate' },
  { label: 'Payer', key: 'from' },
  { label: 'Recipient', key: 'recipient' },
  { label: 'Category', key: 'category' },
  { label: 'Purpose', key: 'purpose' },
  { label: 'Comment', key: 'comment' },
  { label: 'Token', key: 'token' },
  { label: 'Token Name', key: 'tokenName' },
  { label: 'Amount', key: 'amount' },
  { label: 'AmountUSDC', key: 'amountUSDC' },
  { label: 'Transaction Hash', key: 'txHash' },
  { label: 'Payer Address', key: 'from' },
  { label: 'Recipient Address', key: 'recipient' },
]
